import React from "react";
import type { Metadata } from "next";
import "@site/css/globals.css";
import { BackgroundBeams, Footer, Navbar } from "@site/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={params.lang} className="dark">
      <body className="flex h-screen flex-col bg-white text-slate-500 antialiased dark:bg-slate-900 dark:text-slate-400">
        <BackgroundBeams />
        <Navbar />
        <main className="flex-1 sm:pt-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
