import { Sidebar } from "@site/components";
import React from "react";
import { getSidebar } from "@site/navs/documentation";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function DocsLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { slug: string[]; lang: string };
}) {
  const sidebar = getSidebar(params.lang, params.slug);
  return (
    <div className="mx-auto max-w-8xl px-4 sm:px-6 md:px-8">
      <Sidebar sidebarItems={sidebar} />
      <div className="lg:pl-[19.5rem]">{children}</div>
    </div>
  );
}
