name: GitHub Pages

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1
      - run: ./build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
